db.usertype.insertMany([{ userTypeName: "USER" }, { userTypeName: "ADMIN" }]);

db.recipes.insertMany([
  {
    name: "WEGAŃSKIE USZKA NADZIEWANE SOCZEWICĄ",
    dishType: "vegan",
    description:
      "Idealne, postne uszka, które świetnie sprawdzą się w wigilijnym barszczu. Przygotuj te delikatne pierogi pełne aromatycznego farszu, które zaskoczą wszystkich gości!",
    rating: "8.3",
    ingredients: [
      "mąka pszenna",
      "woda",
      "sól",
      "oliwa z oliwek",
      "soczewica czerwona",
      "cebula",
      "papryka wędzona mielona",
      "Ajwar",
      "przyprawa do mięsa",
      "pieprz czarny",
    ],
    nutrients: [
      { title: "Wartość energetyczna na całe (kcal)", value: 4208 },
      { title: "Wartość energetyczna na 1 porcję (kcal)", value: 420 },
      { title: "Tłuszcz (g)", value: 3.6 },
      { title: "Węglowodany (g)", value: 77.3 },
      { title: "Błonnik (g)", value: 4.3 },
      { title: "Białko (g)", value: 18.3 },
    ],
    photo: "",
    creator: "Kuchnia lidla",
    link: "https://kuchnialidla.pl/weganskie-uszka-nadziewane-soczewica",
  },
  {
    name: "WEGAŃSKIE USZKA NADZIEWANE SOCZEWICĄ",
    dishType: "vegan",
    description:
      "Idealne, postne uszka, które świetnie sprawdzą się w wigilijnym barszczu. Przygotuj te delikatne pierogi pełne aromatycznego farszu, które zaskoczą wszystkich gości!",
    rating: "8.3",
    ingredients: [
      "mąka pszenna",
      "woda",
      "sól",
      "oliwa z oliwek",
      "soczewica czerwona",
      "cebula",
      "papryka wędzona mielona",
      "Ajwar",
      "przyprawa do mięsa",
      "pieprz czarny",
    ],
    nutrients: [
      { title: "Wartość energetyczna na całe (kcal)", value: 4208 },
      { title: "Wartość energetyczna na 1 porcję (kcal)", value: 420 },
      { title: "Tłuszcz (g)", value: 3.6 },
      { title: "Węglowodany (g)", value: 77.3 },
      { title: "Błonnik (g)", value: 4.3 },
      { title: "Białko (g)", value: 18.3 },
    ],
    photo: "",
    creator: "Kuchnia lidla",
    link: "https://kuchnialidla.pl/weganskie-uszka-nadziewane-soczewica",
  },
  {
    name: "",
    description: "",
    rating: "",
    ingredients: [],
    nutrients: [],
    photo: "",
    creator: "",
  },
  {
    name: "",
    description: "",
    rating: "",
    ingredients: [],
    nutrients: [],
    photo: "",
    creator: "",
  },
  {
    name: "",
    description: "",
    rating: "",
    ingredients: [],
    nutrients: [],
    photo: "",
    creator: "",
  },
  {
    name: "",
    description: "",
    rating: "",
    ingredients: [],
    nutrients: [],
    photo: "",
    creator: "",
  },
]);

db.users.insertMany([ {
  firstName: "Romek",
  surname: "Makuszyński",
  email: "romek.makuszynski@fitdiet.com",
  password: "romek",
  userType: "USER",
  profilePhoto: "",
  favouriteRecipes: [],
  favouriteIngredients: ["oliwa z oliwek","soczewica czerwona","cebula"],
  dietProgres: [{}, {}, {}],
}])

db.users.insertMany([
  {
    firstName: "Igor",
    surname: "Szałas",
    email: "admin@fitdiet.com",
    password: "admin",
    userType: "ADMIN",
    profilePhoto: "",
    favouriteRecipes: [],
    favouriteIngredients: [],
    dietProgres: [{}, {}, {}],
  },
  {
    firstName: "Romek",
    surname: "Makuszyński",
    email: "romek.makuszynski@fitdiet.com",
    password: "romek",
    userType: "USER",
    profilePhoto: "",
    favouriteRecipes: [],
    favouriteIngredients: ["oliwa z oliwek","soczewica czerwona","cebula"],
    dietProgres: [{}, {}, {}],
  },
  {
    firstName: "",
    surname: "",
    email: "",
    password: "",
    userType: "",
    profilePhoto: "",
    favouriteRecipes: [],
    favouriteIngredients: [],
    dietProgres: [{}, {}, {}],
  },
  {
    firstName: "",
    surname: "",
    email: "",
    password: "",
    userType: "",
    profilePhoto: "",
    favouriteRecipes: [],
    favouriteIngredients: [],
    dietProgres: [{}, {}, {}],
  },
]);

db.posts.insertMany([
  {
    title: "",
    content: "",
    reactions: "",
    comments: [
      {
        commentAuthor: "",
        commentContent: "",
      },
      {
        commentAuthor: "",
        commentContent: "",
      },
      {
        commentAuthor: "",
        commentContent: "",
      },
    ],
  },
]);
